trigger:
  - main

pr: none

variables:
  - group: ugnext

pool:
  vmImage: ubuntu-latest

steps:
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "install -g bun"
      verbose: true
    displayName: "Install bun using npm"

  - script: |
      bun install --frozen-lockfile
    displayName: "Install dependencies using bun"

  - script: |
      bun run scripts/static-build/pre-process.ts
    displayName: "Run pre-processing script before static build"

  - script: |
      bun run build
    env:
      NEXT_STATIC_OUTPUT: "true"
    displayName: "Build site with static export"

  - script: |
      bun run scripts/static-build/post-process.ts
    displayName: "Run post-processing script after static build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "out"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "Archive output folder"

  - publish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
    artifact: ugnext-static
    displayName: "Publish Artifact"
