trigger:
  - main

pr: none

variables:
  - group: ugnext
  - name: BUN_VERSION
    value: "1.3.10"
  - name: BUN_INSTALL_CACHE_DIR
    value: "$(Pipeline.Workspace)/.bun/install/cache"

pool:
  vmImage: ubuntu-latest

steps:
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "install --global bun@$(BUN_VERSION)"
    displayName: "Install bun using npm"

  - task: Cache@2
    inputs:
      key: '"bun" | "$(Agent.OS)" | "$(BUN_VERSION)" | bun.lock'
      restoreKeys: |
        "bun" | "$(Agent.OS)" | "$(BUN_VERSION)"
      path: "$(BUN_INSTALL_CACHE_DIR)"
    displayName: "Cache bun packages"

  - script: |
      bun install --frozen-lockfile
    env:
      BUN_INSTALL_CACHE_DIR: "$(BUN_INSTALL_CACHE_DIR)"
    displayName: "Install dependencies using bun"

  - script: |
      bun run scripts/static-build/pre-process.ts
    displayName: "Run pre-processing script before static build"

  - script: |
      bun run build
    env:
      NEXT_STATIC_OUTPUT: "true"
    displayName: "Build site with static export"

  - script: |
      bun run scripts/static-build/post-process.ts
    displayName: "Run post-processing script after static build"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "out"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "Archive output folder"

  - publish: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
    artifact: ugnext-static
    displayName: "Publish Artifact"
