[install.scopes]
"@fortawesome" = { token = "$FONTAWESOME_PACKAGE_TOKEN", url = "https://npm.fontawesome.com/" }
"@awesome.me" = { token = "$FONTAWESOME_PACKAGE_TOKEN", url = "https://npm.fontawesome.com/" }